services:
  postgres-db:
    image: postgres
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_DB=hotel-db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: